### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by simcha-c** [rmunoz1994/YouToob#2]
users table looks good!

videos table: 
- [x] should have `uploader_id` for now. When you have `channels` implemented then you can change it. For now, keep it as `uploader_id`.

likes table looks good

comments table
- [x] we will be using a polymorphic association for the comments. Please change that on the table.

Great job!!

**Comment by rmunoz1994** [comment]
I looked into polymorphic association.  I have a better idea of how to implement this now, but would it not be simpler and just as effective to just have a parent_comment_id that could potentially be null similar to how we had it on the reddit-clone project? If it's null then it is just a comment on the video which is referenced by video_id, and if it's not then it is nested under the comment with the equivalent parent_comment_id.
