### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by simcha-c** [rmunoz1994/YouToob#4]
videos slice:
- [x] dont need views now since that is a bonus feature.
- [x] uploaderId should be a number, not an array.
- [x] what is the url in the video slice?

users slice:
- [x] are we going to ever show all the videos that the user like on one page? If no, then we dont need the `likedVideoIds` key.
- [x] not going to be doing channels right now. Put it back into the sample state when you start working on that feature.

- [x] comments can have reply comments. Because of that, comments will have a `commentIds` array.

Everything else looks good!

**Comment by rmunoz1994** [comment]
Adjusted Sample State accordingly!
